### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by Fat-Zer**
Here is a branch with suppressing warnings and fixing errors indicating by them

### CODE REVIEW

**Comment by PrzemoF** [comment]
I added 2 in-line comments (please review) and checked the rest of the fixes - they look OK.

**Comment by Fat-Zer** [comment]
yes, it seems you are right, it's better to use fabs() to be on the safe side for all compilers...

**Comment by Fat-Zer** [comment]
I can rebase and remove reverts, also reorder and squash some commits if you care about clear commit history.

**Comment by PrzemoF** [comment]
That's not really my call, but I'd remove reverts and keep separaty type changes (white space fixes, certain compiler warning or others) in separate commits, so no squashing unless it makes logical sense. The reason behind it is to keep commits bisectable and easily revertable if we get some unexpected problems with those changes. (I'm not a FreeCAD core developer, so it's just a suggestion)

**Pull request closed without merging**
